version: '3'
services:

  app-mysql:
    image: mysql:5.7
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: app_mysql_db
      MYSQL_USER: app_username
      MYSQL_PASSWORD: app_pass
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - app-network

  app-php7.4-fpm:
    build: .
    container_name: app-php7.4-fpm
    volumes:
      - ./www/html:/var/www/html
    restart: always
    depends_on:
      - app-mysql
    networks:
      - app-network

  app-nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 80:80
    volumes:
      - ./www/html:/var/www/html
      - /app/nginx.conf:/etc/nginx/nginx.conf
      - /app/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app-php7.4-fpm
    networks:
      - app-network

networks:
  app-network:
